name: Schemas
on:
  workflow_call:
  schedule:
    # Run this every hour
    - cron: "0 * * * *"

jobs:
  schemas:
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: |
          wget https://github.com/neovim/neovim/releases/download/nightly/nvim-linux64.deb -O /tmp/nvim.deb
          sudo dpkg -i /tmp/nvim.deb
      - uses: actions/checkout@v3
      - name: Build
        run: |
          nvim -u NONE -E -R --headless --cmd "set rtp^=." --cmd "packloadall" --cmd "luafile lua/neoconf/build/init.lua" --cmd q
      - name: Push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "chore(build): auto-generate vimdoc, schemas and annotations"
          commit_user_name: "github-actions[bot]"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
          commit_author: "github-actions[bot] <github-actions[bot]@users.noreply.github.com>"
